### ISSUE TITLE
JAWS in Chrome does not honour the space in the "Change" link in the "Check answers" pattern

### ISSUE THREAD

**Issue by shabana-ali** [hmrc/accessibility#35] opened 2020-07-10 14:15 UTC
Potentially change code to use same method as "Add to list" pattern https://design.tax.service.gov.uk/hmrc-design-patterns/add-to-a-list/ (change pattern also on same page to compare)

Code from:

```html
<a class="govuk-link" href="">
  Change
  <span class="govuk-visually-hidden"> xxx</span>
</a>
```

To:

```html
<a class="govuk-link" href="">
  <span aria-hidden="true">Change</span>
  <span class="govuk-visually-hidden">Change xxx</span>
</a>
```

Example of issue in Chrome on JRS:

![screenshot-changelink-nospace](https://user-images.githubusercontent.com/59563139/87164011-17fa2400-c2c0-11ea-85d5-e9f337f7afc2.png)

**Comment by adamliptrot-oc** [comment] 2020-11-17 16:38
Closed as duplicate of https://github.com/hmrc/accessibility/issues/29

**Closed by adamliptrot-oc** 2020-11-17 16:38 UTC
